RECAP/accounts/urls.py
from django.urls import path
from . import views

app_name= 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('follow/<int:person_pk>', views.follow, name='follow'),
]

RECAP/articles/urls.py
from django.urls import path
from .import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('create/', views.create, name="create"),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comment/', views.create_comment, name='create_comment'),
    path('send_cookie', views.send_cookie, name='send'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('explore/', views.explore, name='explore'),
    path('tags/', views.tags, name='tags'),
    path('hashtag/<int:hashtag_pk>', views.hashtag, name='hashtag'),
]

RECAP/recap/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as accounts_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/',include('articles.urls')),
    path('accounts/',include('accounts.urls')),
    path('<username>/', accounts_views.profile, name='profile'),
]

RECAP/recap/templates/base.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <title>Document</title>
</head>
<body>
  {% if user.is_authenticated %}
    <p>현재 접속된 유저 : {{ user.username }}</p>
    <a class="btn btn-info" href="{% url 'profile' user.username %}">마이페이지</a>
    <a class="btn btn-warning" href="{% url 'articles:explore' %}">둘러보기</a>
    <a href="{% url 'articles:create' %}">새글쓰기</a>
    <a class="btn btn-danger" href="{% url 'accounts:logout' %}">로그아웃</a>
    <a class="btn btn-success" href="{% url 'accounts:update' %}">회원정보수정</a>
    <form class="d-inline" action="{% url 'accounts:delete' %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="회원탈퇴" class="btn btn-secondary">
    </form>
  {% else %}
    <a href="{% url 'accounts:signup' %}">회원가입</a>
    <a href="{% url 'accounts:login' %}">로그인</a>
  {% endif %}
  
  {% block body %}
  {% endblock %}
</body>
</html>