wunderlist/todos/urls.py
from django.urls import path
from todos import views


app_name = 'todos'

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('update/<int:pk>/', views.update, name="update"),
    path('delete/<int:pk>/', views.delete, name="delete"),
]

wunderlist/wunderlist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
]

wunderlist/todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length=100)
    due_date = models.DateField()

wunderlist/todos/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from .models import Todo
from .telegram import sendMessage
# Create your views here.
def index(request):
    todos = Todo.objects.all()
    ctx = {
        'todos':todos,
    }
    return render(request, 'todos/index.html', ctx)

def create(request):
    # new와 create를 통합  
    if request.method == 'POST':
        title = request.POST.get('title')
        due_date = request.POST.get('due-date')
        sendMessage(f"할일 : {title}\n기한{due_date}")
        Todo.objects.create(title=title, due_date =due_date)
        return redirect('todos:index')
    else:
        return render(request, 'todos/create.html')
        

def update(request, pk):
    todo = get_object_or_404(Todo, id=pk)
    if request.method == 'POST':
        past_todo = todo.title
        past_date = todo.due_date
        title = request.POST.get('title')
        due_date = request.POST.get('due-date')
        todo.title = title
        todo.due_date = due_date
        todo.save()
        sendMessage(f"변경\n할일 : {past_todo}\n기한{past_date}\n↓\n할일 : {title}\n기한{due_date}")      
        return redirect('todos:index')
    else:
        ctx = {
            'todo':todo,
        }
        return render(request, 'todos/update.html', ctx)

def delete(request, pk):
    todo = get_object_or_404(Todo, id=pk)
    todo.delete()
    return redirect('todos:index')

def telegram(request):
    print(request.method)
    print(request)
    res = request.get_json() 
    text = res.get('message').get('text')
    chat_id = res.get('message').get("chat").get("id")
    base = "https://api.telegram.org"
    method = "setWebhook"
    token = 'bot945387076:AAFFIwIUMDhmxDSn-0-cHrF8He14WpKFlLQ'
    forwarding = "https://16747f7e.ngrok.io"
    string = f'{base}/bot{token}/{method}?url={forwarding}/{token}'
    
    return HttpResponse(200)
    

wunderlist/todos/templates/todos/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>
  {% block title %}

  {% endblock title %}
  </title>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/todos/"><img src="https://img12.androidappsapk.co/300/c/a/9/io.tinbits.memorigi.png" width=80 height=80></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'todos:index' %}">글 모아보기<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'todos:create' %}">글 작성하기</a>
            </li>
          </ul>
        </div>
      </nav>
      {% block body %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

wunderlist/todos/templates/todos/create.html
{% extends 'todos/base.html' %}

{% block body %}
<div class="m-3">
  <h1>Add ToDo</h1>
  <form action="{% url 'todos:create' %}" method="post">
    {% csrf_token %}
    <input type="text" name="title">
    <input type="date" name="due-date">
    <input type="submit">
  </form>
</div>


{% endblock %}

wunderlist/todos/templates/todos/index.html
{% extends 'todos/base.html' %}


{% block title %}
모아보기
{% endblock title %}

{% block body %}

{% for todo in todos  %}
<p>
  
  <a class="btn btn-primary" data-toggle="collapse" href="#multiCollapseExample{{ todo.id }}" role="button"
    aria-expanded="false" aria-controls="multiCollapseExample1">{{ todo.title }} : {{ todo.due_date }}</a>
</p>
<div class="row">
  <div class="col">
    <div class="collapse multi-collapse" id="multiCollapseExample{{ todo.id }}">
      <div class="card card-body">
        하긴 하는거임?
        <a href="{% url 'todos:update' todo.id %}">수정</a>
        <a href="{% url 'todos:delete' todo.id %}">삭제</a>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock %}

wunderlist/todos/templates/todos/update.html
{% extends 'todos/base.html' %}

{% block body %}
<div class="m-3">
  <h1>Edit ToDo</h1>
  <form action="{% url 'todos:update' todo.id %}" method="post">
    {% csrf_token %}
    <input type="text" name="title" value="{{ todo.title }}">
    <input type="date" name="due-date" value="{{ todo.due_date | date:'Y-m-d'}}">
    <input type="submit">
  </form>
</div>
{% endblock %}