PJT07/accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:account_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('follow/<int:person_pk>/', views.follow, name='follow'),
]

PJT07/movies/urls.py
from django.urls import path, include
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/reviews/new/', views.create_review, name='create_review'),
    path('<int:movie_pk>/reviews/<int:review_pk>/delete/', views.delete_review, name='delete_review'),
    path('<int:movie_pk>/like/', views.like, name='like'),


]

PJT07/pjt07/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

PJT07/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class CustomUser(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings', blank=True)

PJT07/movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=30)

class Movie(models.Model):
    title = models.CharField(max_length=50)
    audience = models.IntegerField()
    poster_url = models.CharField(max_length=200)
    description = models.TextField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies', blank=True)

class Review(models.Model):
    content = models.CharField(max_length=200)
    score = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

PJT07/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('email', 'first_name', 'last_name')

PJT07/movies/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('content', 'score',)

PJT07/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import CustomUserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    persons = get_user_model().objects.all()
    context = {
        'persons': persons,
    }
    return render(request, 'accounts/index.html', context)

def detail(request, account_pk):
    person = get_object_or_404(get_user_model(), pk=account_pk)
    make_reviews  = person.review_set.all()
    movies = person.like_movies.all()

    context = {
        'person': person,
        'make_reviews' : make_reviews,
        'movies' : movies,
    }
    return render(request, 'accounts/detail.html', context)

def create(request):
    if request.method == 'POST': 
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:index')
    else:
        form = CustomUserCreationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/create.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'accounts:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/auth_form.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('accounts:index')

@login_required
def follow(request, person_pk):
    person = get_object_or_404(get_user_model(), pk=person_pk)
    user = request.user

    if person.followers.filter(pk=user.pk).exists():
        person.followers.remove(user)
    else:
        #자기자신 follow 막기
        person.followers.add(user)
    return redirect('accounts:detail', person_pk)

PJT07/movies/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Movie, Genre, Review
from .forms import ReviewForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

# Create your views here.
def index(request):
    movies = Movie.objects.all()
    ctx = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', ctx)

def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    review_Form = ReviewForm()

    ctx = {
        'movie': movie,
        'reviews': movie.review_set.all(),
        'review_Form' : review_Form,
    }
    return render(request, 'movies/detail.html', ctx)

@login_required
def create_review(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.movie = movie
            review.user = request.user
            review.save()
    
    return redirect('movies:detail', movie_pk)

@require_POST
@login_required
def delete_review(request, movie_pk, review_pk):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, pk=movie_pk)
        review = get_object_or_404(Review, pk=review_pk)
        if request.user == review.user:
            review.delete()
    return redirect('movies:detail', movie_pk) 
    
@login_required
def like(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    user = request.user
    if movie.like_users.filter(pk=user.pk).exists(): #(2)
        movie.like_users.remove(user)
    else:
        movie.like_users.add(user)
    return redirect('movies:detail', movie_pk)

PJT07/accounts/templates/accounts/auth_form.html
{% extends 'base.html' %}
{% block body %}
    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
{% endblock %}

PJT07/accounts/templates/accounts/create.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'accounts:create' %}" method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
    
{% endblock %}

PJT07/accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block body %}
<h1>{{ person }}</h1>
{% with followers=person.followers.all followings=person.followings.all %}
  {% if user != person %}
    {% if user in followers %}
      <a class="btn btn-outline-primary" href="{% url 'accounts:follow' person.pk %}">언팔로우</a>
    {% else %}
      <a class="btn btn-primary" href="{% url 'accounts:follow' person.pk %}">팔로우</a>
    {% endif %}
  {% endif %}
  <p>팔로워수 : {{ followers | length }} </p>
  <p>
    팔로워 : 
    {% for follower in followers %} 
      {{ follower }}
    {% endfor %}
  </p>
  <p>팔로잉수 : {{ person.followings.count }}</p>
  <p>
    팔로잉 : 
    {% for following in followings %} 
      {{ following }}
    {% endfor %}
  </p>
{% endwith %}
<hr>
<h2> {{ person }}가 쓴 리뷰</h2>
{% with reviews=person.review_set.all %}
  {% for review in reviews %}
  <p>
    내용 : {{ review.content }} | 
    점수 : {{ review.score }} |
  </p>
  {% endfor %}
{% endwith %}

<h2> {{ person }}가 좋아하는 영화</h2>
  {% for movie in person.like_movies.all %}
    {{ movie.title }}
  {% endfor %}
{% endblock %}

PJT07/accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block body %}

{% for person in persons %}
  <p><a href="{% url 'accounts:detail' person.pk %}">{{ person.username }}</a></p>

{% endfor %}










{% endblock %}

PJT07/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block body %}
    <p>영화명: {{ movie.title }}</p>
    <p>누적관객수: {{ movie.audience }}</p>
    <p>포스터 이미지 URL: {{ movie.poster_url }}</p>
    <p>영화소개: {{ movie.description }}</p>
    {% if user.is_authenticated %}
       <form action="{% url 'movies:create_review' movie.pk %}" method='POST'>
           {% csrf_token %}
            {{ review_Form }}
            <input type="submit">
        </form>
        
    {% endif %}

    <h2>좋아요 목록 </h2>
    <p>좋아요 : {{ movie.like_users.count  }}</p>
    {% with likers=movie.like_users.all %}
      <p>좋아요 목록 : 
        {% for u in likers %}
          {{ u }}
        {% endfor %}
      </p>
      {% if user in likers %}
        <a href="{% url 'movies:like' movie.pk %}">좋아요 취소</a>
      {% else %}
        <a href="{% url 'movies:like' movie.pk %}">좋아요!</a>
      {% endif %}
    {% endwith %}

    {% for review in reviews %}
        <p>{{ review.content }} {{ review.score }} {{ review.user }} {{ review.movie.title }}</p>
        <form action="{% url 'movies:delete_review' movie.pk review.pk  %}" method='POST'>
                {% csrf_token %}
            <input type="submit" value="삭제">
        </form>
    {% endfor %}

{% endblock %}

PJT07/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block body %}
    {% for movie in movies %}
        <p>{{ movie.title }}</p>
        <p><a href="{% url 'movies:detail' movie.pk %}"><img height='100px' width='100px' src="{{ movie.poster_url }}" alt="{{ movie.title }}"></a></p>
    {% endfor %}


{% endblock %}

PJT07/pjt07/templates/base.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'accounts:create' %}">회원가입</a>
    <a href="{% url 'accounts:login' %}">로그인</a>
    <a href="{% url 'accounts:logout' %}">로그아웃</a>
    {{ user.username }}
    {% block body %}
    {% endblock %}
</body>
</html>