BOARD/board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
]

BOARD/posts/urls.py
from django.urls import path, include
from . import views

app_name='posts'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('update/<int:pk>', views.update, name='update'),
    path('delete/<int:pk>', views.delete, name='delete'),
]

BOARD/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

BOARD/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post

# Create your views here.
def index(request):
    ctx = {
        'posts': Post.objects.all(),
    }
    return render(request, 'posts/index.html', ctx)


def create(request):
    if request.method == 'POST':
        post = Post()
        post.title = request.POST.get('title')
        post.content = request.POST.get('content')
        post.save()
        return redirect('posts:index')
    else:
        return render(request,'posts/create.html')

def detail(request, pk):
    ctx = {
        'post': Post.objects.get(id=pk),
    }
    return render(request, 'posts/detail.html', ctx)

def update(request, pk):
    post = get_object_or_404(Post, id=pk)
    if request.method == 'POST':
        post.title = request.POST.get('title')
        post.content = request.POST.get('content')
        post.save()
        return redirect('posts:index')
    else:
        ctx = {
            'post': post
        }
        return render(request, 'posts/update.html', ctx)

def delete(request, pk):
    post = Post.objects.get(id=pk)
    post.delete()
    return redirect('posts:index')

BOARD/posts/templates/posts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  {% block body%}
  {% endblock%}
</body>
</html>

BOARD/posts/templates/posts/create.html
{% extends 'posts/base.html' %}

{% block body %}
<a href="/posts/create/">글 작성하기</a>
<a href="/posts/index/">글 모아보기</a>

<form action="{% url 'posts:create' %}" method="POST">{% csrf_token %}
  <input type="text" name="title">
  <textarea name="content">콘텐츠 입력해주세요</textarea>
  <button type="submit">제출</button>
</form>

{% endblock %}

BOARD/posts/templates/posts/detail.html
{% extends 'posts/base.html' %}

{% block body %}
<a href="/posts/create/">글 작성하기</a>
<a href="/posts/index/">글 모아보기</a>

<h1>{{ post.title }}</h1>
<h1>{{ post.content }}</h1>
<h1>{{ post.created_at }}</h1>
<h1>{{ post.updated_at }}</h1>

<a href="{% url 'posts:update' post.id %}">글 수정하기</a>

{% endblock%}

BOARD/posts/templates/posts/index.html
{% extends 'posts/base.html' %}

{% block body %}
<a href="/posts/create/">글 작성하기</a>
<a href="/posts/index/">글 모아보기</a>

{% for post in posts %}
<li>
  <a href="{% url 'posts:detail' post.id %}">{{ post.title }}</a>
</li>
{% endfor %}
{% endblock %}

BOARD/posts/templates/posts/update.html
{% extends 'posts/base.html' %}

{% block body %}
<a href="/posts/create/">글 작성하기</a>
<a href="/posts/index/">글 모아보기</a>

<form action="{% url 'posts:update' post.id %}" method="POST">{% csrf_token %}
  <input type="text" name="title" value="{{ post.title }}">
  <textarea name="content">{{ post.content }}</textarea>
  <button type="submit">제출</button>
</form>

{% endblock %}